DROP VIEW VIEW_GRADE_CHECK;
DROP SEQUENCE SEQ_STUDENT_NO;
DROP SEQUENCE SEQ_PROF_NO;
DROP SEQUENCE SEQ_ENROLL_NO;
DROP SEQUENCE SEQ_LECTURE_NO;
DROP SEQUENCE SEQ_LECTURE_JUG_NO;
DROP SEQUENCE SEQ_GRADE_NO;
DROP TRIGGER TRG_STUDENT_DEL;

CREATE SEQUENCE SEQ_STUDENT_NO
START WITH 20220001
INCREMENT BY 1
MAXVALUE 20229999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_PROF_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_ENROLL_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_LECTURE_NO
START WITH 001
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_LECTURE_JUG_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_GRADE_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE VIEW VIEW_GRADE_CHECK
AS
SELECT
       D.LECTURE_NAME LECTURE_NAME,
       B.PROF_NAME PROF_NAME,
       A.STUDENT_NO STUDENT_NO,
       C.STUDENT_NAME STUDENT_NAME,
       A.ATT_SCORE ATT_SCORE,
       A.ASS_SCORE ASS_SCORE,
       A.MID_SCORE MID_SCORE,
       A.FIN_SCORE FIN_SCORE,
       A.GRADE GRADE
  FROM GRADE A
  JOIN PROFESSOR B
    ON A.PROF_NO = B.PROF_NO
  JOIN STUDENT C
    ON A.STUDENT_NO = C.STUDENT_NO
  JOIN LECTURE D
    ON A.LECTURE_NO = D.LECTURE_NO;
    
CREATE OR REPLACE TRIGGER TRG_STUDENT_DEL_01
    BEFORE DELETE ON STUDENT
    FOR EACH ROW
BEGIN
    INSERT INTO STUDENT_DEL
    VALUES(:OLD.STUDENT_NO, :OLD.DEPT_CODE, :OLD.STUDENT_ID, :OLD.STUDENT_PWD, :OLD.STUDENT_NAME, :OLD.ADDRESS, :OLD.STUDENT_TELNO, :OLD.EMAIL, :OLD.ENROLL_DATE, DEFAULT, 'Y');
END;
/

INSERT INTO DEPARTMENT VALUES ('PSY', '심리학과');
INSERT INTO DEPARTMENT VALUES ('CHE', '화학공학과');
INSERT INTO DEPARTMENT VALUES ('COM', '컴퓨터공학과');
INSERT INTO DEPARTMENT VALUES ('ELE', '전기공학과');
INSERT INTO DEPARTMENT VALUES ('ENG', '영어영문학과');
INSERT INTO DEPARTMENT VALUES ('ECO', '경제학과');
INSERT INTO DEPARTMENT VALUES ('PHY', '체육학과');
INSERT INTO DEPARTMENT VALUES ('BUS', '경영학과');
INSERT INTO DEPARTMENT VALUES ('GEC', '교양학부');

INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'PSY', 'USER00', 'USER00', '확인용', NULL, '01011112222', NULL, DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'CHE', 'USER01', 'USER01', '김수영', '경기도 시흥시', '01011113333', 'ksy01@naver.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'ELE', 'USER02', 'USER02', '서진수', '서울시 강동구', '01011114444', 'sjs01@naver.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'CHE', 'USER03', 'USER03', '오수재', '서울시 영등포구', '01011115555', 'osj35@naver.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'COM', 'USER04', 'USER04', '이정호', '경기도 구리', '01011116666', 'ljh01@naver.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'ECO', 'USER05', 'USER05', '유지석', '서울시 강남구', '01011117777', 'yjs01@gmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'PHY', 'USER06', 'USER06', '이호리', '제주도 서귀포시', '01011118888', 'lhr01@gmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'BUS', 'USER07', 'USER07', '정중앙', '서울시 강서구', '01011119999', 'jja01@hanmail.net', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'PSY', 'USER08', 'USER08', '하동운', '서울시 강북구', '01022229999', 'hdw01@hanmail.net', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'ECO', 'USER09', 'USER09', '길성주', '서울시 양천구', '01022228888', 'gsj01@hotmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'CHE', 'USER10', 'USER10', '손지동', '서울시 금천구', '01022227777', 'sjd01@gmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'ELE', 'USER11', 'USER11', '구운모', '서울시 노원구', '01022226666', 'gwm01@gmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'PSY', 'USER12', 'USER12', '김태연', '충청도 태안', '01022225555', 'kty01@naver.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'ENG', 'USER13', 'USER13', '정근오', '경기도 일산', '01022224444', 'jgh01@naver.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'ENG', 'USER14', 'USER14', '김철수', '경기도 파주', '01022223333', 'kcs01@naver.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'PHY', 'USER15', 'USER15', '박경운', '강원도 강릉 ', '01022222222', 'pkw01@gmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'PHY', 'USER16', 'USER16', '박진서', '서울시 동작구 ', '01022221111', 'pjs01@gmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'COM', 'USER17', 'USER17', '강지녕', '울산시 남구', '01033331111', 'kjs01@gmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'BUS', 'USER18', 'USER18', '김창운', '전라남도 순천시', '01033332222', 'kcw01@gmail.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'CHE', 'USER19', 'USER19', '엄태연', '서울시 관악구', '01033333333', 'uth01@naver.com', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES
(SEQ_STUDENT_NO.NEXTVAL, 'CHE', 'USER20', 'USER20', '유군오', '서울시 은평구', '01033334444', 'ygh01@naver.com', DEFAULT, DEFAULT);


INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'PSY', 'prof01', 'prof01', '오심리', '서울시 동작구', '01011112222', 'osl01@naver.com', '01/01/01', DEFAULT);
INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'CHE', 'prof02', 'prof02', '김화공', '경기도 시흥시', '01077778888', 'ksy85@gmail.com', '14/07/26', DEFAULT);
INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'COM', 'prof03', 'prof03', '이컴공', '서울시 신길동', '01044445555', 'ljh02@gmail.com', '15/02/04', DEFAULT);
INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'ELE', 'prof04', 'prof04', '서전기', '서울시 강동구', '01066669999', 'sjs03@yahoo.com', '10/07/07', DEFAULT);
INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'ENG', 'prof05', 'prof05', '최영어', '대구시 경산시', '01088882222', 'cis88@gmail.com', '15/07/20', DEFAULT);
INSERT INTO PROFESSOR VALUES
(SEQ_PROF_NO.NEXTVAL, 'ECO', 'prof06', 'prof06', '한경제', '강원도 속초시', '01012342222', 'hgj99@gmail.com', '20/01/20', DEFAULT);
INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'PHY', 'prof07', 'prof07', '공체육', '경기도 용인시', '01012347777', 'gcy12@gmail.com', '21/01/20', DEFAULT);
INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'BUS', 'prof08', 'prof08', '하경영', '서울시 경복궁', '01099999999', 'hgy12@gmail.com', '03/12/29', DEFAULT);
INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'GEC', 'prof09', 'prof09', '허수학', '인천시 가좌동', '01000009999', 'hsh44@gmail.com', '09/11/29', DEFAULT);
INSERT INTO PROFESSOR VALUES 
(SEQ_PROF_NO.NEXTVAL, 'GEC', 'prof10', 'prof10', '정과학', '시흥시 거모동', '0112457464', 'jgh77@gmail.com', '07/07/07', DEFAULT);










